// AUTO-GENERATED by scripts/genScenes.mjs from ../script.json. Do not hand-edit;
// edit script.json and re-run the generator instead.
export type Scene = {
  id: string;
  image: string | null;
  eyebrow: string;
  title: string;
  narration: string;
  seconds: number;
};

export const FPS = 30;

export const APP_NAME = "Acme Rewards";
export const TAGLINE = "Every visit, rewarded.";

export const BRAND = {
  primary: "#4F46E5",
  primaryLight: "#6D5EF0",
  primaryDark: "#2E27A8",
  gold: "#F59E0B",
  silver: "#C0C0C0",
  platinum: "#5E6973",
  bg: "#F4F5F9",
  surface: "#FFFFFF",
  textPrimary: "#1F2340",
  textSecondary: "#8A8DA6",
  success: "#16A34A",
};

export const scenes: Scene[] = [
  {
    id: "intro",
    image: null,
    eyebrow: "ACME REWARDS",
    title: "A Sample Walkthrough",
    narration:
      "This is Acme Rewards, a fictional demo app. This short walkthrough shows exactly what the app-walkthrough skill produces: a narrated video and a matching PDF guide, built from real screenshots.",
    seconds: 14,
  },
  {
    id: "onboarding",
    image: "01_onboarding.png",
    eyebrow: "GETTING STARTED",
    title: "Your Digital Card",
    narration:
      "New members are welcomed with a short onboarding flow explaining the app's core idea: a secure rotating QR code that proves membership everywhere partners are.",
    seconds: 12,
  },
  {
    id: "signin",
    image: "02_signin.png",
    eyebrow: "SIGN IN",
    title: "Welcome Back",
    narration:
      "Returning members sign in with an email and password. First-time visitors can create an account right from the same screen.",
    seconds: 9,
  },
  {
    id: "home",
    image: "03_home.png",
    eyebrow: "HOME TAB",
    title: "The Digital Card",
    narration:
      "The home tab is the heart of the app: a Gold-tier membership card with a live QR code, ready to scan at checkout.",
    seconds: 9,
  },
  {
    id: "browse",
    image: "04_browse.png",
    eyebrow: "OFFERS TAB",
    title: "Browse Every Offer",
    narration:
      "The offers tab lists every active discount across the partner network, filterable by category, with flagship partners pinned to the top.",
    seconds: 11,
  },
  {
    id: "detail",
    image: "05_detail.png",
    eyebrow: "OFFER DETAILS",
    title: "Every Term, Up Front",
    narration:
      "Tapping into an offer shows the exact discount, its validity window, and a one-tap way to show proof at the counter.",
    seconds: 9,
  },
  {
    id: "settings",
    image: "06_settings.png",
    eyebrow: "SETTINGS",
    title: "Total Control",
    narration:
      "Settings covers appearance, security, and account management, all in one place.",
    seconds: 7,
  },
  {
    id: "outro",
    image: null,
    eyebrow: "ACME REWARDS",
    title: "That's the Idea",
    narration:
      "That's a complete example: real screens, a written narration script, local text to speech, and a rendered video, plus a matching styled PDF guide. Point this skill at your own app to build the real thing.",
    seconds: 14,
  },
];

export const totalSeconds = scenes.reduce((sum, s) => sum + s.seconds, 0);
